language: php
php:
- '5.6'
- '7.0'
- '7.1'
matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: precise
script: vendor/bin/phpunit
before_install: composer install
env:
  matrix:
    secure: Ub4c3ghVirtBTLPFNypqI4u1M7klCcesMsTdYlgYa+u6xnnOKXQvzpx3WsmA/zl71mZSJwuqH1lSKtGFg06GCbfq1P7aOXctnKGRINDY4dpEJqQJHV2qXsL3dCXYeypYNDwfG94bHsGf10FIu8fKdYJviuHpyLOZYO+EpjqfEzwxJJhWCbLyeKhaO1Ot6jlYK7KBAd4IBHrvuqT8hyYGGaqaLkC/8qqRwhftr+15NCWIeHuDCEjp4mclSaSpAaOSZeNrDOR9pVe0xu96ca6MUFS6DJREYwQSWRhJnO0OvwOt047jfdY5CnfmHI/Q/2odiP6iJbR+Go/dfl491+7eXInPlkaN0pVHGwrxewVjljLnlvpj9zhIWlSi+n7tf62htpJ1zIpfrxkLUF4gyS+hcaJ9WNiLmokqDZ/uxdbtHyA61cIPjBjJLf86KaLTNMNO2paQde4y0qx/vwp47PsLMly7cYFugHff+vnqjMCgtdsx3DhawOSHu4u9qqrjcNHGnp412P/0tUSrZySZbYaLPnnxh74CY28SCNuEBVr54HubHN/EpGRVuCcGMjVlGsGSkD5Y2DcBKEsTfdyozozOvV/zDiuWb5vfoimhxfUujDxO31RneKxyOITGj1LfJlLYYj/jE1kXyjvaTySdlTQKxtKEB5XoNmq9SbXPy1t7BWk=
